name: Deploy 31ngo to server

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
            path: node_modules
            key: ${{ runner.os }}-npm-cache
            restore-keys: |
              ${{ runner.os }}-npm-cache
      - name: Install Dependencies
        run: yarn install
      - name: Build App
        run: yarn build
        env:
          CI: false
      - name: Upload App Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package31ngo
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download App Artifact
        uses: actions/download-artifact@v2
        with:
          name: package31ngo
      - name: Copy dist files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./dist/*
          target: /home/${{ secrets.SSH_USERNAME }}/app/
