version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ../../
      dockerfile: ops/docker/app/Dockerfile
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    networks:
      default:
        aliases:
          - 31ngo.local
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ../../
      dockerfile: ops/docker/server/Dockerfile
    working_dir: /app
    volumes:
      - ../../ws/:/app
      - /app/node_modules
    ports:
      - '8083:8080'
    environment:
      - DB_CONN=mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb
    networks:
      default:
        aliases:
          - 31ngo-server.local
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - type: bind
        source: ./data
        target: /data/db

