version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ../../
      dockerfile: ops/docker/app/Dockerfile
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - 31ngo.local
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ../../
      dockerfile: ops/docker/server/Dockerfile
    working_dir: /app
    volumes:
      - ../../ws/:/app
      - /app/node_modules
    ports:
      - 8083:80
    environment:
      - DB_CONN=mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb
      - APP_ENV=${SERVER_APP_ENV}
      - WS_PORT=${WS_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      default:
        aliases:
          - 31ngo-server.local
    depends_on:
      - mongodb

  mongodb:
    container_name: db
    image: mongodb/mongodb-community-server:7.0.1-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

